# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2adef69e045ba4ce9230d650542e31a"
name = "kit"
handle = "kit-2"
application_url = "https://aims-has-photographers-silver.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://aims-has-photographers-silver.trycloudflare.com/auth/callback", "https://aims-has-photographers-silver.trycloudflare.com/auth/shopify/callback", "https://aims-has-photographers-silver.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
